<h1>18 June HW</h1>

In [63]:
import pandas as pd

In [64]:
df=pd.read_csv("C:\\Users\\abhishek maurya\\Desktop\\loanf.csv")

In [109]:
df.head(4)

Interest.Rate  FICO.Score  Loan.Length  Monthly.Income  Loan.Amount
6           15.31         670           36         4891.67         6000
11          19.72         670           36         3575.00         2000
12          14.27         665           36         4250.00        10625
13          21.67         670           60        14166.67        28000

In [110]:
df.fillna(0)

Interest.Rate  FICO.Score  Loan.Length  Monthly.Income  Loan.Amount
6             15.31         670           36         4891.67         6000
11            19.72         670           36         3575.00         2000
12            14.27         665           36         4250.00        10625
13            21.67         670           60        14166.67        28000
21            21.98         665           36         6666.67        22000
23            17.99         665           60         4100.00         6500
25            16.82         670           60         4500.00         4000
40            12.49         660           36         3448.33         2400
41            17.27         670           36         2500.00         3200
43            19.13         660           36        12000.00         5500
44            21.74         660           36         3700.00        15650
48            23.91         670           60        11250.00        20000
52            17.44         660           36         7952.00         3000
54            21.49         665           60         4166.67        22250
57            12.98         670           36         1100.00         2500
64            15.80         665           36         3250.00         9000
74            17.27         665           36         4583.33        12000
75            15.31         670           36         3833.33         6000
76            13.12         670           36         5000.00         6725
79            17.77         665           36         2500.00        10000
91            16.29         665           36         2000.00         7925
93            15.81         670           36         2666.67         9525
99            19.72         665           36         4166.67        10375
100           18.75         670           36         5833.33         4800
114           13.99         660           36         5000.00         5750
132           16.32         665           36         4600.00         7500
136           16.40         660           36         4166.67         7500
142           23.28         660           60         7083.33        18000
147           17.27         660           36         3833.33         3000
151           21.49         670           36        12500.00        30000
...             ...         ...          ...             ...          ...
2348           6.62         750           36         9666.67        12000
2349           6.99         780           36         2500.00        10000
2359           6.62         805           36         9166.67        32550
2362           7.62         805           36         2500.00         7125
2366          10.37         785           60         5833.33        14000
2375           7.51         765           36         3000.00         4500
2385           7.29         740           36         6250.00        12000
2386          11.83         755           36        12000.00        24250
2389           6.03         775           36        13750.00        10000
2396           7.88         800           60         4750.00         9000
2397          14.09         750           60         6666.67        31825
2399           8.94         815           36         2833.33        12800
2400          13.99         745           60         4167.00        20000
2410           6.99         775           36         5166.67         7000
2411           6.03         790           36         5836.67        11000
2413          10.99         740           36        12500.00        24000
2422           5.79         760           36         5416.67         5000
2429          13.49         745           60         4166.67        25000
2438           9.88         750           36         3338.00        16750
2445           6.62         750           36        11666.67        13000
2447           8.90         740           36         5641.67        11400
2453           7.90         765           36         7500.00        25000
2454      

In [111]:
df["Interest.Rate"].max()

24.89

In [112]:
from sklearn.linear_model import LinearRegression

In [113]:
from sklearn.model_selection import train_test_split

In [114]:
df.describe()

Interest.Rate   FICO.Score  Loan.Length  Monthly.Income   Loan.Amount
count    2500.000000  2500.000000  2500.000000     2499.000000   2500.000000
mean       13.066996   705.888000    41.260800     5688.931321  12406.500000
std         4.178230    35.033161     9.930893     3963.118185   7801.544872
min         5.420000   640.000000    36.000000      588.500000   1000.000000
25%        10.160000   680.000000    36.000000     3500.000000   6000.000000
50%        13.110000   700.000000    36.000000     5000.000000  10000.000000
75%        15.800000   725.000000    36.000000     6800.000000  17000.000000
max        24.890000   830.000000    60.000000   102750.000000  35000.000000

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2500 entries, 6 to 2497
Data columns (total 5 columns):
Interest.Rate     2500 non-null float64
FICO.Score        2500 non-null int64
Loan.Length       2500 non-null int64
Monthly.Income    2499 non-null float64
Loan.Amount       2500 non-null int64
dtypes: float64(2), int64(3)
memory usage: 197.2 KB


In [140]:
x=df[["FICO.Score","Loan.Amount"]].values
x

array([[  670,  6000],
       [  670,  2000],
       [  665, 10625],
       ...,
       [  810, 27000],
       [  765, 25000],
       [  740, 16000]], dtype=int64)

In [141]:
type(df)

pandas.core.frame.DataFrame

In [142]:
y=df.iloc[:,0].values
y

array([15.31, 19.72, 14.27, ...,  6.62, 10.75, 14.09])

In [143]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.2)

In [144]:
len(x_train)

2000

In [145]:
model=LinearRegression()

In [146]:
#y_train=y_train.reshape(1,-1)

In [147]:
model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [148]:
y_train

array([23.76, 13.06, 22.47, ..., 13.11, 13.11, 19.72])

In [155]:
model.predict([[665,10625]])

array([16.33362677])

In [153]:
a=int(input("ENter your FICO score"))
b=int(input("ENter your Loan  amount"))

ENter your FICO score665
ENter your Loan  amount10625


In [154]:
print("your intest rate is {}".format(model.predict([[a,b]])))

your intest rate is [16.33362677]
